# Host configuration for blue-pc system
{ ... }:
{
  # Import required configuration modules
  imports = [
    # Hardware-specific configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix
    # Core system modules shared across all hosts
    ./../../modules/core
  ];

  # Set CPU frequency governor to performance mode for better responsiveness
  # Options: "ondemand", "powersave", "performance", "conservative"
  powerManagement.cpuFreqGovernor = "performance";
}
