general {
    lock_cmd = pidof hyprlock || hyprlock   # avoid spawning multiple instances
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false             # respect fullscreen video / games
}

listener {
    timeout = 1800                          # 30 min: lock screen
    on-timeout = loginctl lock-session
}

listener {
    timeout = 2100                          # 35 min: displays off
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
